elk:
  image: sebp/elk
  ports:
    - "8089:8089"
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  environment:
    - vm.max_map_count=262144
  volumes:
    - ./scripts:/etc/elasticsearch/scripts
    - ./logstash:/etc/logstash/conf.d
